### ISSUE TITLE
Telegram Web App seems to be dead

### ISSUE THREAD

**Issue by GrimbiXcode** [meetfranz/recipe-telegram#14]
The repo of the [Telegram Web App](https://github.com/zhukov/webogram) only gets the necessary dependency update but no feature updates.

I don't know a reasonable way to integrate the Telegram Desktop Application into Franz or rather into the Electron Framework. Or does anyone know a solution?

Without a solution Telegram in Franz will probably not be usable for long.

**Comment by Stanzilla** [comment]
I think they are working on https://github.com/evgeny-nadymov/telegram-react now, you can make a custom recipe with that but you'll have to fix up the notification code as well

**Comment by GrimbiXcode** [comment]
Thank you, that's great to know.

**Comment by Stanzilla** [comment]
I made this, https://github.com/Stanzilla/recipe-telegram, it works okay ish

**Comment by hongshaoyang** [comment]
> I made this, https://github.com/Stanzilla/recipe-telegram, it works okay ish

Please make a PR for this! I tried it out and it's so much prettier! :D

**Comment by Stanzilla** [comment]
> > I made this, [Stanzilla/recipe-telegram](https://github.com/Stanzilla/recipe-telegram), it works okay ish
> 
> Please make a PR for this! I tried it out and it's so much prettier! :D

It's not really production ready
